project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - href: ss3.qmd
        text: Jupyter Notebook
      - href: ql.qmd
        text: Quarto Live

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
